/* SPDX-License-Identifier: MIT */
/*
 * Copyright(c) 2019-2020 Intel Corporation.
 *
 */

#ifndef NETLINK_H_INCLUDED
#define NETLINK_H_INCLUDED

#define INTERFACE_VERSION 1

enum cmd {
	CMD_UNSPEC,
	CMD_L0_SMI,
	_CMD_MAX,
};

enum cmd_rsp_type {
	RESPONSE,
	RESPONSE_PARTIAL,
};

enum cmd_op {
	OP_DEVICE_ENUM,
	OP_PORT_ENABLE,
	OP_PORT_DISABLE,
	OP_PORT_STATE_QUERY,
	OP_PORT_USAGE_ENABLE,
	OP_PORT_USAGE_DISABLE,
	OP_PORT_USAGE_STATE_QUERY,
	OP_PORT_BEACON_ENABLE,
	OP_PORT_BEACON_DISABLE,
	OP_PORT_BEACON_STATE_QUERY,
	OP_PORT_ROUTED_QUERY,
	OP_REM_REQUEST,
	OP_ROUTING_GEN_QUERY,
	OP_FABRIC_DEVICE_PROPERTIES,
	OP_SUB_DEVICE_PROPERTIES_GET,

	_CMD_OP_MAX,
};

enum attr {
	ATTR_UNSPEC,

	/* operation to execute */
	ATTR_CMD_OP,

	ATTR_CMD_OP_CONTEXT,
	ATTR_CMD_OP_RESULT,
	ATTR_CMD_OP_RSP_TYPE,

	/* Attributes for SD identification */
	ATTR_FABRIC_ID,
	ATTR_SD_INDEX,

	ATTR_PAD,

	ATTR_ENTRIES,

	/* Attributes for fabric devices */
	ATTR_FABRIC_DEVICE,

	ATTR_DEV_NAME,
	ATTR_PARENT_DEV_NAME,

	ATTR_SOCKET_ID,
	ATTR_PCI_SLOT_NUM,
	ATTR_SUBDEVICE_COUNT,
	ATTR_VERSION,
	ATTR_PRODUCT_TYPE,

	ATTR_SUB_DEVICE,

	/* Attributes for sub devices */
	ATTR_ID,
	ATTR_GUID,
	ATTR_EXTENDED_PORT_COUNT,
	ATTR_FABRIC_PORT_COUNT,
	ATTR_SWITCH_LIFETIME,
	ATTR_ROUTING_MODE_SUPPORTED,
	ATTR_ROUTING_MODE_ENABLED,
	ATTR_EHHANCED_PORT_0_PRESENT,

	ATTR_FABRIC_PORT,

	ATTR_FABRIC_PORT_NUMBER,
	ATTR_FABRIC_PORT_TYPE,

	ATTR_BRIDGE_PORT_NUMBER,

	ATTR_ENABLED_STATE,

	ATTR_ROUTING_GEN_START,
	ATTR_ROUTING_GEN_END,

	_ATTR_MAX,
};

void nl_term(void);
int nl_init(void);

#endif
