# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

savage-y := savage_drv.o savage_bci.o savage_state.o

obj-$(CPTCFG_DRM_SAVAGE)+= savage.o

