# SPDX-License-Identifier: GPL-2.0
# For building individual subdir files on the command line
subdir-ccflags-y += -I$(backport_srctree)/$(src)/..

# Extra header tests
header-test-pattern-$(CPTCFG_DRM_I915_WERROR) := *.h
