# SPDX-License-Identifier: GPL-2.0

imxdrm-objs := imx-drm-core.o ipuv3-crtc.o ipuv3-plane.o

obj-$(CPTCFG_DRM_IMX) += imxdrm.o

obj-$(CPTCFG_DRM_IMX_PARALLEL_DISPLAY) += parallel-display.o
obj-$(CPTCFG_DRM_IMX_TVE) += imx-tve.o
obj-$(CPTCFG_DRM_IMX_LDB) += imx-ldb.o

obj-$(CPTCFG_DRM_IMX_HDMI) += dw_hdmi-imx.o
