# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for hisilicon drm drivers.
# Please keep this list sorted alphabetically

obj-$(CPTCFG_DRM_HISI_HIBMC) += hibmc/
obj-$(CPTCFG_DRM_HISI_KIRIN) += kirin/
